name: GitHub-Profile-3D-Contrib

on:
  schedule: # Run at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        with:
          SETTING_JSON: |
            {
              "type": "normal",
              "backgroundColor": "#1a1b27",
              "foregroundColor": "#9e9e9e",
              "strongColor": "#00c0a0",
              "weakColor": "#505050",
              "radarColor": "#00c0a0",
              "growingAnimation": true,
              "contribColors": [
                "#404040",
                "#00c0a0",
                "#00a080",
                "#008060",
                "#006040"
              ],
              "username": "Aaron_Murillo01"
            }
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated" || exit 0
          git push
